const products=[
{id:1,name:'Recycled Planter',cat:'Garden',price:499,points:1900,emoji:'🪴',material:'Made from 8 recycled bottles',rating:4.8},
{id:2,name:'Eco Chair',cat:'Furniture',price:2999,points:12000,emoji:'🪑',material:'Made from 32 recycled bottles',rating:4.7},
{id:3,name:'Recycled Backpack',cat:'Clothing',price:1799,points:7000,emoji:'🎒',material:'Made from 20 recycled bottles',rating:4.6},
{id:4,name:'Desk Organizer',cat:'Office',price:699,points:3200,emoji:'🗂️',material:'Made from 5 recycled bottles',rating:4.9},
{id:5,name:'Eco Storage Box',cat:'Home Decor',price:899,points:3600,emoji:'📦',material:'Made from 11 recycled bottles',rating:4.5},
{id:6,name:'Recycled Notebook',cat:'Stationery',price:299,points:1200,emoji:'📓',material:'Made with recycled plastic covers',rating:4.8},
{id:7,name:'Garden Stool',cat:'Garden',price:1299,points:5200,emoji:'🪑',material:'Made from 18 recycled bottles',rating:4.6},
{id:8,name:'Kids Building Set',cat:'Kids Toys',price:799,points:3100,emoji:'🧩',material:'Made from recycled PP plastic',rating:4.7}
];
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
const API=(window.RECYCLR_CONFIG?.API_BASE_URL||'').replace(/\/$/,'');
const getToken=()=>localStorage.getItem('recyclrToken')||'';
function toast(msg){let t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>t.classList.remove('show'),2500)}
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(getToken())headers.Authorization=`Bearer ${getToken()}`;const r=await fetch(`${API}${path}`,{...options,headers});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.error||'Request failed');return data}
function getCart(){return JSON.parse(localStorage.getItem('recyclrCart')||'[]')} function saveCart(c){localStorage.setItem('recyclrCart',JSON.stringify(c));updateCartCount()}
function updateCartCount(){let n=getCart().reduce((a,b)=>a+b.qty,0);$$('[data-cart-count]').forEach(e=>e.textContent=n)}
function addToCart(id){let c=getCart(),x=c.find(i=>i.id===id);x?x.qty++:c.push({id,qty:1});saveCart(c);toast('Added to cart 🛒')}
function renderProducts(list=products,target='#products'){let el=$(target);if(!el)return;if(!list.length){el.innerHTML='<div class="card empty-state"><div style="font-size:44px">🔎</div><h3>No products found</h3><p class="muted">Try changing your search or filters.</p></div>';return}el.innerHTML=list.map(p=>`<div class="card product-card"><div class="product-img">${p.emoji}</div><div class="muted">${p.cat}</div><h3>${p.name}</h3><p class="muted">${p.material}</p><div><span class="stars">★ ${p.rating}</span> <span class="muted">(120+)</span></div><p><b class="price">₹${p.price.toLocaleString('en-IN')}</b> <span class="muted">or ${p.points.toLocaleString()} pts</span></p><button class="btn primary" onclick="addToCart(${p.id})">Add to Cart</button></div>`).join('')}
function initShop(){if(!$('#products')||!$('#search'))return;const apply=()=>{const q=$('#search').value.trim().toLowerCase(),cat=$('#category')?.value||'All',price=Number($('#priceFilter')?.value||0),rating=Number($('#ratingFilter')?.value||0),sort=$('#sortFilter')?.value||'featured';let list=products.filter(p=>(!q||(p.name+' '+p.cat+' '+p.material).toLowerCase().includes(q))&&(cat==='All'||p.cat===cat)&&(!price||p.price<=price)&&(!rating||p.rating>=rating));if(sort==='newest')list.sort((a,b)=>b.id-a.id);if(sort==='rating')list.sort((a,b)=>b.rating-a.rating||a.price-b.price);if(sort==='price-low')list.sort((a,b)=>a.price-b.price);if(sort==='price-high')list.sort((a,b)=>b.price-a.price);renderProducts(list);if($('#filterCount'))$('#filterCount').textContent=`${list.length} product${list.length===1?'':'s'}`};['search','category','priceFilter','ratingFilter','sortFilter'].forEach(id=>{const el=$('#'+id);if(el){el.addEventListener('input',apply);el.addEventListener('change',apply)}});$('#clearFilters')?.addEventListener('click',()=>{['search'].forEach(id=>$('#'+id).value='');['category','priceFilter','ratingFilter','sortFilter'].forEach((id,i)=>$('#'+id).value=['All','0','0','featured'][i]);apply()});apply()}
function renderCart(){let el=$('#cartItems');if(!el)return;let c=getCart();if(!c.length){el.innerHTML='<div class="card" style="text-align:center;padding:50px"><div style="font-size:55px">🛍️</div><h2>Your cart is empty</h2><p class="muted">Find something made from recycled plastic.</p><a class="btn primary" href="shop.html">Start Shopping</a></div>';if($('#subtotal'))$('#subtotal').textContent='₹0';return}let total=0;el.innerHTML=c.map(i=>{let p=products.find(x=>x.id===i.id),sum=p.price*i.qty;total+=sum;return `<div class="cart-row"><div class="cart-thumb">${p.emoji}</div><div><b>${p.name}</b><div class="muted">₹${p.price.toLocaleString('en-IN')}</div></div><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><b>${i.qty}</b><button onclick="changeQty(${p.id},1)">+</button></div><b>₹${sum.toLocaleString('en-IN')}</b></div>`}).join('');if($('#subtotal'))$('#subtotal').textContent='₹'+total.toLocaleString('en-IN');if($('#checkoutAmount'))$('#checkoutAmount').textContent='₹'+total.toLocaleString('en-IN')}
function changeQty(id,d){let c=getCart(),x=c.find(i=>i.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)c=c.filter(i=>i.id!==id);saveCart(c);renderCart()}
function initRecycle(){let w=$('#weight'),pts=$('#estimatedPoints'),type=$('#plasticType');function calc(){let rate={PET:50,HDPE:45,PVC:35,LDPE:30,PP:40,PS:25}[type?.value||'PET'];if(pts)pts.textContent=Math.round((w?.value||5)*rate)+' pts'}w?.addEventListener('input',()=>{$('#weightValue').textContent=w.value+' kg';calc()});type?.addEventListener('change',calc);$('#recycleForm')?.addEventListener('submit',async e=>{e.preventDefault();let kg=Number(w.value||5),points=Number((pts.textContent||'0').replace(/\D/g,''));const f=e.currentTarget;const date=f.querySelector('input[type=date]')?.value,time=f.querySelector('input[type=time]')?.value,address=f.querySelector('textarea')?.value.trim();if(!date||!time||!address)return toast('Please enter pickup date, time and address');const payload={plasticType:type?.value||'PET',weightKg:kg,pickupDate:date,pickupTime:time,address,points};try{if(getToken()&&API){const d=await api('/api/pickups',{method:'POST',body:JSON.stringify(payload)});localStorage.setItem('lastPickup',JSON.stringify(d.pickup));toast(`Pickup scheduled! +${points} points estimated 🎉`)}else{localStorage.setItem('lastPickup',JSON.stringify({...payload,status:'Scheduled',date:new Date().toLocaleDateString()}));toast(`Pickup saved locally. Connect the backend to sync it. +${points} points 🎉`)}setTimeout(()=>location.href='tracking.html',700)}catch(err){toast(err.message)}});calc()}
async function initAuth(){const login=$('#loginForm'),signup=$('#signupForm');if(login)login.addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:login.elements.email.value,password:login.elements.password.value})});localStorage.setItem('recyclrToken',d.token);localStorage.setItem('recyclrUser',JSON.stringify(d.user));location.href=d.user.verified?'dashboard.html':'otp.html'}catch(err){toast(err.message)}});if(signup)signup.addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('/api/auth/signup',{method:'POST',body:JSON.stringify({name:signup.name.value,email:signup.email.value,phone:signup.phone.value,password:signup.password.value})});localStorage.setItem('recyclrToken',d.token);localStorage.setItem('recyclrUser',JSON.stringify({name:signup.name.value,email:signup.email.value,verified:false}));if(d.devOtp)localStorage.setItem('recyclrDevOtp',d.devOtp);location.href='otp.html'}catch(err){toast(err.message)}})}
async function initOtp(){const f=$('#otpForm');if(!f)return;const send=async()=>{try{const d=await api('/api/auth/send-otp',{method:'POST'});if(d.devOtp){localStorage.setItem('recyclrDevOtp',d.devOtp);if($('#devOtp'))$('#devOtp').textContent=`Development OTP: ${d.devOtp}`};toast('OTP sent ✓')}catch(err){toast(err.message)}};await send();f.addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/auth/verify-otp',{method:'POST',body:JSON.stringify({code:f.elements.code.value})});localStorage.removeItem('recyclrDevOtp');toast('Verified successfully ✓');setTimeout(()=>location.href='dashboard.html',500)}catch(err){toast(err.message)}});$('#resendOtp')?.addEventListener('click',send);const d=localStorage.getItem('recyclrDevOtp');if(d&&$('#devOtp'))$('#devOtp').textContent=`Development OTP: ${d}`}
async function initCheckout(){const f=$('#checkoutForm');if(!f)return;if(!getToken()){toast('Please login before checkout');setTimeout(()=>location.href='login.html?next=checkout.html',700);return}f.addEventListener('submit',async e=>{e.preventDefault();const amount=getCart().reduce((sum,i)=>sum+(products.find(p=>p.id===i.id)?.price||0)*i.qty,0);if(!amount)return toast('Your cart is empty');try{const order=await api('/api/payments/order',{method:'POST',body:JSON.stringify({amount:amount*100})});if(!window.Razorpay)throw new Error('Payment checkout is unavailable');const rz=new Razorpay({key:order.keyId,amount:order.amount,currency:order.currency,name:'Recyclr',description:'Recycled products order',order_id:order.orderId,prefill:{name:f.fullName.value,email:JSON.parse(localStorage.getItem('recyclrUser')||'{}').email||'',contact:f.phone.value},theme:{color:'#15803D'},handler:async response=>{try{await api('/api/payments/verify',{method:'POST',body:JSON.stringify(response)});localStorage.removeItem('recyclrCart');toast('Payment verified 🎉');setTimeout(()=>location.href='dashboard.html',700)}catch(err){toast(err.message)}}});rz.open()}catch(err){toast(err.message)}})}
function initTheme(){if(localStorage.getItem('dark')==='1')document.body.classList.add('dark');$$('[data-theme]').forEach(b=>b.onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('dark',document.body.classList.contains('dark')?'1':'0')})}
function initForms(){$$('form[data-demo]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();toast('Saved successfully ✓')}));$('#logout')?.addEventListener('click',()=>{localStorage.removeItem('recyclrUser');localStorage.removeItem('recyclrToken');location.href='index.html'});$('#copyReferral')?.addEventListener('click',()=>{navigator.clipboard?.writeText('RECYCLE250');toast('Referral code copied!')})}
document.addEventListener('DOMContentLoaded',()=>{updateCartCount();initTheme();initForms();initShop();renderCart();initRecycle();initAuth();initOtp();initCheckout();$$('[data-demo-action]').forEach(b=>b.onclick=()=>toast(b.dataset.demoAction));let u=JSON.parse(localStorage.getItem('recyclrUser')||'null');$$('[data-user]').forEach(e=>e.textContent=u?.name||'Anant');});
